# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "brady"
client_id = "<your-client-id>"
application_url = "https://<your-app-url>.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://<your-app-url>.trycloudflare.com/auth/callback",
  "https://<your-app-url>.trycloudflare.com/auth/shopify/callback",
  "https://<your-app-url>.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "<your-dev-store-url>.myshopify.com"
